### ISSUE TITLE
Runtime or layer for CLI applications

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#120]
With v0.3 we get rid of the principle where we have `bref.php` that receives every event and decides what to execute ("is it a HTTP call, simple lambda event or CLI execution?").

Now we have 2 runtimes:

- PHP
- PHP-FPM

What's missing from Bref v0.2 is the ability to run console commands (Symfony Console or Laravel Artisan) in a lambda.

To keep that feature we could create a runtime that makes it super easy to do so.

For example:

```yaml
...
Resources:
    ConsoleFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: bin/console
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:us-east-2:416566615250:layer:php-cli-72:1'
```

(notice the handler is `bin/console` and the PHP runtime is `php-72-cli`, not `php-72`)

In that layer we would have a `bootstrap` that takes the incoming event and convert it to a CLI call.

The only thing that would differ from the `php-72` runtime is the `bootstrap` so we could either:

- create a separate `php-72-cli` runtime
- create a layer that only overrides the `/opt/bootstrap` file (so you use the `php-72` layer *plus* the `php-cli` layer on top of it), it might be easier to maintain

WDYT?
