### ISSUE TITLE
Unable to push to SQS

### ISSUE THREAD

**Issue by pmayet** [mnapoli/bref#183]
Framework Lumen : 5.7
Bref : 0.3
Bref Layer :  eu-west-1 php-cli

When I test with SAM local, no problem.

But when I deploy my Lambda, I can't push to SQS, and I have no error.

Event SQS => Lambda => Push SQS

I have tested with sqs connection (driver sqs) and with the package for driver sqs-plain (dusterio/laravel-plain-sqs).

Any idea ?

**Comment by mnapoli** [comment]
No idea really, are you adding specific policies to `template.yaml` to authorize your function to push into SQS?

Can you confirm it's a PHP function (not the `console` layer)?

**Comment by pmayet** [comment]
Yes I confirm, PHP Function

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'my-function'
            Description: ''
            CodeUri: .
            Handler: index.php
            MemorySize: 512
            Timeout: 10 # Timeout in seconds
            Runtime: provided
            Events:
                    QueueMessages:
                        Type: SQS
                        Properties:
                            Queue: 'arn:aws:sqs:eu-west-1:AWS_ACCOUNT_ID:SQS_QUEUE'
                            BatchSize: 10
            Layers:
                - 'arn:aws:lambda:eu-west-1:416566615250:layer:php-72:5'
```
