### ISSUE TITLE
Deployment question

### ISSUE THREAD

**Issue by prolic** [mnapoli/bref#199]
Hi have everything set up (I think) and I can execute my script locally with:
`php index.php my_function`

But when I try to run this:
`./vendor/bin/bref cli my_function`

I receive the following output:
```
START RequestId: 58b08ea0-77ee-4599-a0a4-60a3d3db7f2e Version: $LATEST
END RequestId: 58b08ea0-77ee-4599-a0a4-60a3d3db7f2e
REPORT RequestId: 58b08ea0-77ee-4599-a0a4-60a3d3db7f2e  Duration: 1001.28 ms    Billed Duration: 1000 ms       Memory Size: 128 MB     Max Memory Used: 25 MB
2019-01-21T16:05:15.188Z 58b08ea0-77ee-4599-a0a4-60a3d3db7f2e Task timed out after 1.00 seconds



                                                                                               
 [ERROR] 2019-01-21T16:05:15.188Z 58b08ea0-77ee-4599-a0a4-60a3d3db7f2e Task timed out after    
         1.00 seconds
```

Any idea what's wrong?

**Comment by nealio82** [comment]
Can you post your `index.php` and `template.yaml` so we can debug / reproduce please? :)

**Comment by prolic** [comment]
index.php

```
<?php declare(strict_types=1);

namespace HMC\Bref;

use Silly\Application;
use Symfony\Component\Console\Output\OutputInterface;

require __DIR__.'/vendor/autoload.php';

$silly = new Application();

$silly->command('bi.visits.v1 [timeout]', function (int $timeout, OutputInterface $output): void {
    require __DIR__ . '/functions/bi/visits/v1/error.php';
    require __DIR__ . '/functions/bi/visits/v1/eventAppeared.php';
    require __DIR__ . '/functions/bi/visits/v1/index.php';

    $output->writeln(functions\bi\visits\v1\index($timeout));
});

$silly->run();
```

template.yaml:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'HMC Bref'
Resources:
    bref:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: bref
            CodeUri: .
            Handler: index.php
            Timeout: 10 # Timeout in seconds
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:us-east-1:416566615250:layer:php-72:15'
            Environment:
                Variables:
                    ES_CONNECTION_STRING: 'connectTo=tcp://eventstore:1113;DefaultUserCredentials=admin:changeit'
                    ES_USERNAME: 'admin'
                    ES_PASSWORD: 'changeit'
    brefs:
        Type: 'AWS::S3::Bucket'
```
