### ISSUE TITLE
Documentation: Security Groups

### ISSUE THREAD

**Issue by prolic** [mnapoli/bref#201]
Maybe it's my job to read more about CloudFormation Lambda Templates, but it will surely be a help for many others as well.

I need add my lambda to an existing security group, so it can access specific resources (f.e. an RDS or ElastiCache). Other may need to add a new security group to their lambdas. Same with subnets of course.

**Comment by pmayet** [comment]
It depends on your network breakdown, but you add the VPCAccessPolicy policy, and you specify the default SG of your VPC, as well as the subnets.
CAUTION: A lambda in a mail order takes longer to start, because a network interface must be mapped.

```
Policies:
    - VPCAccessPolicy: {}
VpcConfig:
    SecurityGroupIds:
        - 'sg-id'
    SubnetIds:
        - 'subnet-id-az-a'
        - 'subnet-id-az-b'
        - 'subnet-id-az-c'
```
