### ISSUE TITLE
Connection refused while trying to join unix:///tmp/.bref/php-fpm.sock

### ISSUE THREAD

**Issue by italo1983** [mnapoli/bref#220]
I'm using Slim framework with bref v0.3 and mysql extension loaded to query on Aurora Serverless
Layer: arn:aws:lambda:eu-central-1:416566615250:layer:php-72-fpm:4
Some endpoints using mysql query are returning 502 with this error:
**Fatal error: Uncaught Hoa\Socket\Exception\Exception: Client returns an error (number 111): Connection refused while trying to join unix:///tmp/.bref/php-fpm.sock. in /var/task/vendor/hoa/socket/Client.php:191**
How i can solve this error??

**Comment by mnapoli** [comment]
Could you try with the latest runtimes: https://runtimes.bref.sh/ (watch out the whole name has changed, not just the version)

Once you have tried: do you have any other logs before that?

Could you also try to run locally to see if you have other results? (see https://bref.sh/docs/local-development.html)

**Comment by italo1983** [comment]
I've solved the problem, seems that Slim does not terminate the request when the database does not respond so the fpm socket is busy and does not work (return Internal server error) until the function restart. After applying the right permissions to the lambda group the function started to work perfectly!
Tested on brief 0.3 and Slim 2 with php-fpm72:4
Thank you for the great work on this great project!

**Comment by mnapoli** [comment]
Oh that's interesting.

Maybe what we could try is have the PHP timeout (max_execution_time) at 29 seconds, and the lambda will be at 30 seconds.

That way we are certain the PHP process will always be shutdown before the lambda shuts down.

I'll keep this issue open to remember to implement that.

**Comment by j-tec** [comment]
> I've solved the problem, seems that Slim does not terminate the request when the database does not respond so the fpm socket is busy and does not work (return Internal server error) until the function restart. After applying the right permissions to the lambda group the function started to work perfectly!
> Tested on brief 0.3 and Slim 2 with php-fpm72:4
> Thank you for the great work on this great project!

Can you describe what permissions you added to your lambda?

**Comment by mnapoli** [comment]
Moving my comment here from https://github.com/mnapoli/bref/issues/214#issuecomment-460558637

> OK thank you, that makes sense then. We should modify the PHP max execution time to 29 seconds then.
>
> Any other idea to address this (e.g. if users change the API Gateway timeout below 30 seconds) is welcome. Maybe we could use the `context` variable (not available in Bref in the current version) to determine how much time is left and update the PHP max execution time on the fly.

**Comment by j-tec** [comment]
To set the max_execution_time to 29 seconds did not work for me. As long as this lambda is warm, I'm not able to get it work again, even the actions with no database connectionm - which worked fine before this error.

**Comment by mnapoli** [comment]
OK this is good to know @j-tec. Just to be sure did you set 29 seconds in php.ini (not template.yaml)?

**Comment by j-tec** [comment]
Yes, and i can confirm that the php.ini is loaded with 29 seconds max_execution_time.

**Comment by deleugpn** [comment]
I'm getting this one at the moment.

```
Fatal error: Uncaught Hoa\Socket\Exception\Exception: Client returns an error (number 111): Connection refused while trying to join unix:///tmp/.bref/php-fpm.sock. in /var/task/vendor/hoa/socket/Client.php:191
22:43:01 Stack trace:
22:43:01 #0 /var/task/vendor/hoa/stream/Stream.php(219): Hoa\Socket\Client->_open('unix:///tmp/.br...', NULL)
22:43:01 #1 /var/task/vendor/hoa/stream/Stream.php(297): Hoa\Stream\Stream::_getStream('unix:///tmp/.br...', Object(Hoa\Socket\Client), NULL)
22:43:01 #2 /var/task/vendor/hoa/stream/Stream.php(178): Hoa\Stream\Stream->open()
22:43:01 #3 /var/task/vendor/hoa/socket/Connection/Connection.php(197): Hoa\Stream\Stream->__construct('unix:///tmp/.br...', NULL)
22:43:01 #4 /var/task/vendor/hoa/fastcgi/Responder.php(183): Hoa\Socket\Connection\Connection->connect()
22:43:01 #5 /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php(102): Hoa\Fastcgi\Responder->send(Array, '')
22:43:01 #6 /opt/bootstrap(26): Bref\Runtime\PhpFpm->proxy(Array)
22:43:01 #7 /var/task/vendor/mnapoli/bref/src/Runtime/LambdaRuntime.php(58): {closure}(Array)
22:43:01 #8 /opt/bootstrap(27): Bref\Runtime\LambdaRuntime->processNextEvent(Object(Closure))
```

**Comment by deleugpn** [comment]
Turns out the problem does seem to be related to some process hanging longer than the maximum timeout. For me it was because of MySQL access. Since PDO takes longer than 30 seconds to timeout and the Lambda was outside the VPC (without access to Aurora), the fpm process would just hang in the first run and never work. By deploying a new lambda inside the VPC, the problem went away because the MySQL timeout went away.

**Comment by gonzalovilaseca** [comment]
@deleugpn I'm facing the same issue, I've added the RDS VPC to the Lambda config, and redeployed the function but issue is still there, did you have to do anything else?

**Comment by deleugpn** [comment]
Here's my lambda: 

```
  Api:
    Type: AWS::Serverless::Function
    Properties:
      Handler: public/index.php
      Runtime: provided
      Layers:
        - arn:aws:lambda:eu-west-1:209497400698:layer:php-72-fpm:2
      CodeUri: ./
      MemorySize: 1024
      Timeout: 30
      Role: !ImportValue LambdaExecutionRoleArn
      Policies:
        - AWSLambdaFullAccess
      VpcConfig:
        SecurityGroupIds: [!ImportValue AllowAllAddressesContainerSecurityGroup]
        SubnetIds: !Split [',', !ImportValue PrivateSubnets]
      Events:
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
```

Here's my Lambda Role. Note that if your lambda doesn't interact with S3 or SQS, you only need the EC2 for VPC ENI provisioning:

```
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: allowLambdaLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: allowSqs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:ChangeMessageVisibility
            - s3:Put*
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            Resource:
            - '*'
```

Here's the Lambda Security Group. Note that Egress is what the message is talking about. Allowing the lambda to go out to the internet. If you don't need inboud, feel free to erase the Ingress.

```
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from Load Balancer
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: '-1'
          IpProtocol: '-1'
          ToPort: '-1'
      SecurityGroupIngress:
        - FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
          SourceSecurityGroupId: !Ref GeneralPurposeLoadBalancerSecurityGroup
      VpcId: !ImportValue Vpc
```
