### ISSUE TITLE
Website: add anchors to titles

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#240]
In the documentation titles (h1, h2, etc.) have IDs. It makes it possible to link to a sub-section of a page directly, for example: https://bref.sh/docs/#use-cases

However it's not easy to find the URL, we have to look into the source of the page.

A better solution would be to have a clickable anchor link next to each title.

I did that on php-di.org, for example here: http://php-di.org/doc/container-configuration.html#production-environment

The way it works is via [a piece of JS code](https://github.com/PHP-DI/PHP-DI/blob/9054cf14c4dd214c2b91fa55317cf179ebca7226/website/default.twig#L108-L112):

```js
                // Add anchors to headers
                $('article h2, article h3, article h4, article h5').each(function () {
                    var url = document.URL.replace(/#.*$/, "") + '#' + $(this).attr('id');
                    $(this).append(' <a class="anchor" href="' + url + '">#</a>');
                });
```

and [CSS](https://github.com/PHP-DI/PHP-DI/blob/cdcf21d2a8a60605e81ec269342d48b544d0dfc7/website/less/main.less#L126-L133):

```css
    .anchor {
        position: absolute;
        margin-left: -25px;
        left: 0;
    }
    a.anchor:hover {
        text-decoration: none;
    }
```

I also added this piece of CSS to add some room so that the title is visible in the page:

```css
    // Offset so that the title is not hidden behind the nav bar
    *[id]:before {
        display: block;
        content: " ";
        margin-top: -75px;
        height: 75px;
        visibility: hidden;
    }
```

We could reuse some of that code (and maybe adapt the style a little bit) to add the same thing here.

It is really useful when trying to point someone to a specific piece of documentation.

The Twig template for documentation pages is here: https://github.com/mnapoli/bref/blob/master/website/template/default.twig

To run the website locally checkout this repository and run `make website-preview`.
