### ISSUE TITLE
Document dealing with CORS

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/bref#252]
I am opening this issue so that we document this information.

When building an API on Lambda (+ API Gateway) we often need to enable CORS so that it can be called from the browser (e.g. with a SPA).

There is a very simple option in SAM (in `template.yaml`) to do that:

```yaml
Globals:
    Api:
        Cors: "'*'"
```

However **it doesn't work with `sam local` yet!** (it works when deployed though)

The issue to track that in the SAM repository: https://github.com/awslabs/aws-sam-cli/issues/323 There is a pull request as well: https://github.com/awslabs/aws-sam-cli/pull/1009

## Workaround

A workaround is to deal with CORS in the PHP API.

Here is an example for a Slim application:

```
composer require eko3alpha/slim-cors-middleware
```

```php
$app = new \Slim\App();
$app->add(new \Eko3alpha\Slim\Middleware\CorsMiddleware([
    '*' => ['GET', 'POST'],
]));

// ...
```

**Comment by Luitame** [comment]
That PR (awslabs/aws-sam-cli#1009) mentioned above was closed and the work in progress related to CORS is living here awslabs/aws-sam-cli#1242

**Comment by mnapoli** [comment]
With `serverless.yml` it seems even simpler: https://serverless.com/framework/docs/providers/aws/events/apigateway/#enabling-cors

```yaml
functions:
  hello:
    handler: index.php
    layers:
        - ${bref:layer.php-73-fpm}
    events:
      - http:
          path: '/'
          method: ANY
          cors: true
```

**Comment by FrancescoArcieri** [comment]
Can you provide also an example of serverless.yml using httpAPI?

**Comment by RTC1** [comment]
> Can you provide also an example of serverless.yml using httpAPI?

Is it possible with httpApi - can't see it documented?

**Comment by mnapoli** [comment]
Short version:

```yaml
provider:
    httpApi:
        cors: true
```

If anyone wants to add that to the Bref documentation that would be neat.
