### ISSUE TITLE
Load extension dynamically

### ISSUE THREAD

**Issue by t-geindre** [mnapoli/bref#26]
As done in #14 with `opcache.so`, I tried to load more extensions dynamically.

I was able to compile Redis and MongoDB extensions with a bit tweaked version of `bin/php/Dockerfile` and `bin/php/build.sh`.

Then I created a tar archive containing those two extensions in the `ext` directory.

And finally I used the following hook to make php binary load those extensions:

```yaml
hooks:
    build:
        # Add custom extensions to php.ini
        - 'echo "extension=mongodb.so" >> .bref/php.ini'
        - 'echo "extension=redis.so" >> .bref/php.ini'
```

A `phpinfo()` confirms that those two extensions are correctly loaded.

I think this could be done in a better way, especially the `php.ini` update.

What do you think?

**Comment by t-geindre** [comment]
I had idea: each php archive could provide its own `php.ini` file, allowing it to load all provided extensions, included opcache.

**Comment by mnapoli** [comment]
This is a nice solution. However we could also go with a solution similar to, for example, platform.sh: https://docs.platform.sh/languages/php/ini.html

We could allow to set php.ini values in `.bref.yml`, for example:

```yaml
php:
    configuration:
        memory_limit: 256M
```

For enabling extensions:

```yaml
php:
    extensions:
        - mongodb
        - redis
```

I am 100% for building and including standard extensions into Bref, I just don't want to enable all of them by default to avoid slowing down PHP's start time (since we start a PHP process on every request).

So if we are talking about redis and mongodb I think it would be way better to build them in [build.sh](https://github.com/mnapoli/bref/blob/master/bin/php/build.sh#L26) and the Dockerfile by default, and enable them with `.bref.yml` as shown above.

Later, if someone wants to build its own custom extension, then we can find a solution. But I think it's a rare use case, it's fine if we don't address it right now.

What do you think?
