### ISSUE TITLE
"PHP-FPM has already been started" on any Symfony PHP call making a PDO connection

### ISSUE THREAD

**Issue by parsingphase** [mnapoli/bref#265]
Not sure this is a specific, identifiable issue in itself, whether it relates to any other FPM timeout / RDS 
issues currently ongoing, or whether it can shed light on any of these. Please let me know if I can usefully provide more info or try anything like a new layer version.

I note (relating also to twitter discussions with @nealio82) that there are two security models for RDS/VPC interaction, depending on how long the relevant AWS account has been using RDS for (note: not just how old the AWS account is): https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.FindDefaultVPC.html

My specific error is as follows:

From a single API call within a Symfony 3.4 app, itself making single PDO connection to a mysql instance inside a VPC. App returns with `{"message": "Internal server error"}`

RDS has: Public accessibility: Yes

The RDS instance is accessible with the same credentials from a remote mysql client.

I can't figure out how I'd directly tell if the MySQL connection is actually being made by the Lambda, or if it's just timing out.

Logs from CloudWatch 

```
[11-Mar-2019 19:06:07] NOTICE: fpm is running, pid 8
[11-Mar-2019 19:06:07] NOTICE: ready to handle connections
START RequestId: 30c32c12-bbbe-464f-ae55-9597a36fa0ea Version: $LATEST
END RequestId: 30c32c12-bbbe-464f-ae55-9597a36fa0ea
REPORT RequestId: 30c32c12-bbbe-464f-ae55-9597a36fa0ea	Init Duration: 277.33 ms	Duration: 30030.15 ms	Billed Duration: 30400 ms Memory Size: 1024 MB	Max Memory Used: 122 MB	
2019-03-11T19:06:37.178Z 30c32c12-bbbe-464f-ae55-9597a36fa0ea Task timed out after 30.03 seconds

PHP Fatal error: Uncaught Exception: PHP-FPM has already been started, aborting in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php:50
Stack trace:
#0 /opt/bootstrap(22): Bref\Runtime\PhpFpm->start()
#1 {main}
thrown in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php on line 50

Fatal error: Uncaught Exception: PHP-FPM has already been started, aborting in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php:50
Stack trace:
#0 /opt/bootstrap(22): Bref\Runtime\PhpFpm->start()
#1 {main}
thrown in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php on line 50
```

Template file:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'com-weightinwhales-lambda-php'
            Description: ''
            CodeUri: .
            Handler: web/app.php
            Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
            MemorySize: 1024 # The memory size is related to the pricing and CPU power
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-73-fpm:2'
            Events:
                # The function will match all HTTP URLs
                HttpRoot:
                    Type: Api
                    Properties:
                        Path: /
                        Method: ANY
                HttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY

    AssetsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: 'assets.weightinwhales.com'
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
            CorsConfiguration:
                CorsRules:
                    - AllowedMethods:
                        - GET
                      AllowedOrigins:
                        - !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
                        - http://127.0.0.1:3000

# Outputs show up in the CloudFormation dashboard
Outputs:
    DemoHttpApi:
        Description: 'URL of our function in the *Prod* environment'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
```
