### ISSUE TITLE
Could not initialize PHP FPM. PHP-FPM failed to start

### ISSUE THREAD

**Issue by Sh1d0w** [mnapoli/bref#286]
I've followed the guide to [set up console function](https://bref.sh/docs/runtimes/console.html). I am using Laravel so this is piece of my config:

```yaml
LaravelArtisan:
        Type: 'AWS::Serverless::Function'
        Properties:
            FunctionName: artisan-prod
            CodeUri: .
            Handler: artisan
            Runtime: provided
            Timeout: 900
            MemorySize: 3008
            Role: !GetAtt LaravelFunctionExecutionRole.Arn
            Layers:
                - 'arn:aws:lambda:eu-central-1:209497400698:layer:php-73:3'
                - 'arn:aws:lambda:eu-central-1:209497400698:layer:console:3'
            VpcConfig:
                SecurityGroupIds: !Ref SecurityGroupIds
                SubnetIds: !Ref SubnetIds
            Policies:
                -
                    VPCAccessPolicy: {  }

```

However if I execute any artisan command, e.g.

```
vendor/bin/bref cli artisan-prod --region=eu-central-1 -- help
```

I get

```
START RequestId: dfb66e0c-f925-4873-9c79-b0d958bb9d71 Version: $LATEST
Cold Start
sh: line 0: exec: php-fpm: not found
{"errorMessage":"Could not initialize PHP FPM. PHP-FPM failed to start","errorType":"InvalidPhpFpmInitialization"}
END RequestId: dfb66e0c-f925-4873-9c79-b0d958bb9d71
REPORT RequestId: dfb66e0c-f925-4873-9c79-b0d958bb9d71	Duration: 253.20 ms	Billed Duration: 300 ms 	Memory Size: 3008 MB	Max Memory Used: 47 MB
Unknown application error occurred
```

Any ideas how I can solve this or further debug it will be much appreciated.
