### ISSUE TITLE
Exception is thrown unless translations are explicitly defined

### ISSUE THREAD

**Issue by nealio82** [mnapoli/bref#40]
Following the documentation for Symfony / Bref config, an exception is thrown by the application and logged in CloudWatch as:

```
Fatal error: Uncaught UnexpectedValueException: /var/task/translations defined in translator.paths does not exist or is not a directory in /var/task/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:989
Stack trace:
#0 /var/task/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php(247): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->registerTranslatorConfiguration(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder), Object(Symfony\Component\DependencyInjection\Loader\XmlFileLoader))
#1 /var/task/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#2 /var/task/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Com in /var/task/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php on line 989
```

The default `config/packages/translation.yml` file in the `symfony/website-skeleton` application looks as follows:

```
framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
```

Changing it to the following fixes the problem, but reduces flexibility.

```
framework:
    default_locale: 'en'
    translator:
        fallbacks: ['en']
```

From what I've tried this isn't as simple as just setting an environment variable in the Lambda console (unless I'm doing it wrong?). Maybe some note in the documentation will be helpful?

**Comment by mnapoli** [comment]
Thanks for the report. It seems that Symfony complains that the `translations` directory does not exist at the root of the project (`/var/task/translations` -> `/var/task` is the projet root on AWS lambda).

Did you add the `translations` directory in `serverless.yml`? Else it will not be deployed by default. Maybe this could be added to the documentation if it's "just" that?

**Comment by nealio82** [comment]
The problems appears to persist, although your explanation make sense.

current `serverless.yml`:

```
service: test

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - '*'
    - '**'
  include:
    - bref.php
    - 'src/**'
    - 'vendor/**'
    - composer.json # Symfony uses it to figure out the root directory
    - 'bin/**'
    - 'config/**'
    - 'var/cache/prod/**' # We want to deploy the production caches
    - 'translations'

functions:
  # By default we create one "main" function
  main:
    handler: handler.handle
    timeout: 20 # Timeout in seconds, the default is 6 seconds
    # The function will match all HTTP URLs
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
    environment:
      APP_ENV: 'prod'
      APP_DEBUG: '0'
```

```
Fatal error: Uncaught UnexpectedValueException: /var/task/translations defined in translator.paths does not exist or is not a directory in /var/task/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:989
Stack trace:
#0 /var/task/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php(247): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->registerTranslatorConfiguration(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder), Object(Symfony\Component\DependencyInjection\Loader\XmlFileLoader))
#1 /var/task/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#2 /var/task/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Com in /var/task/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php on line 989```

Current content of `translations/` is currently just `.gitignore`
